php:
  image: php:7-fpm
  volumes:
    - './:/usr/src/app'

nginx:
  image: nginx:latest
  links:
    - php
  ports:
    - "8080:80"
  volumes:
    - './public:/usr/src/app'
    - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

